'use strict';
const $=id=>document.getElementById(id);
const templates=[
{name:'思い出・旅行',icon:'✈',sub:'旅のはじまりから、余韻まで',chapters:['出発・到着','場所・体験','人物・食事','ハイライト','余韻'],weights:[38,110,60,60,20]},
{name:'学校・行事',icon:'⚑',sub:'取り組みと交流の記録',chapters:['準備','行事スタート','活動・交流','成果','振り返り'],weights:[38,25,155,45,25]},
{name:'成長記録',icon:'↗',sub:'挑戦から、いまの姿へ',chapters:['スタート','挑戦','継続・変化','成果','現在'],weights:[40,70,95,50,30]},
{name:'商品・お店紹介',icon:'▣',sub:'魅力と利用のイメージを伝える',chapters:['サービス概要','特徴','利用イメージ','強み','ご案内'],weights:[38,100,70,45,35]},
{name:'お祝い・感謝',icon:'♡',sub:'大切な人へ、思いを届ける',chapters:['これまで','思い出','人とのつながり','ベストショット','感謝'],weights:[65,75,70,45,30]}];
let photos=[],template=0,time=0,playing=false,recording=false,raf=0,last=0,plan=[],total=300,audioFile=null,audioURL=null,audioEl=null,audioCtx=null,audioSource=null,destination=null,recorder=null,downloadURL=null,wake=null,cancelled=false;
const canvas=$('canvas'),ctx=canvas.getContext('2d');
function clock(n){n=Math.floor(n);return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
function say(s){$('status').textContent=s;}
function drawTemplates(){ $('templates').replaceChildren();templates.forEach((t,i)=>{const b=document.createElement('button');b.className='template'+(i===template?' active':'');b.setAttribute('aria-pressed',i===template);b.innerHTML=`<span class="icon">${t.icon}</span><span><strong>${t.name}</strong><small>${t.sub}</small></span><span class="check">${i===template?'✓':''}</span>`;b.onclick=()=>{if(recording)return;template=i;photos.forEach(p=>p.chapter=null);drawTemplates();compose();};$('templates').append(b);});}
function invalidate(){if(downloadURL){URL.revokeObjectURL(downloadURL);downloadURL=null;}$('download').hidden=true;}
function compose(){pause();invalidate();time=0;total=Number($('length').value);$('seek').max=total;
const t=templates[template];const weights=t.weights.reduce((a,b)=>a+b,0);photos.forEach((p,i)=>{if(p.chapter===null){let f=(i+.5)/photos.length,c=0;for(let j=0;j<t.weights.length;j++){c+=t.weights[j]/weights;if(f<=c){p.chapter=j;break;}}}});
const active=t.chapters.map((name,i)=>({name,i,items:photos.filter(p=>p.chapter===i)})).filter(g=>g.items.length);
const opening=Math.min(8,total*.05),remaining=total-opening;const sum=active.reduce((s,g)=>s+t.weights[g.i],0);plan=[];let start=opening;
active.forEach(g=>{const budget=remaining*t.weights[g.i]/sum;g.items.forEach(p=>{const duration=budget/g.items.length;plan.push({p,start,end:start+duration,duration,chapter:g.name});start+=duration;});});if(plan.length)plan[plan.length-1].end=total;
canvas.width=$('ratio').value==='wide'?1280:720;canvas.height=$('ratio').value==='wide'?720:1280;$('spec').textContent=`${canvas.width} × ${canvas.height}`;
$('empty').hidden=!!photos.length;['play','seek','compose','export'].forEach(id=>$(id).disabled=!photos.length);$('summary').textContent=`写真 ${photos.length}枚 · ${t.name}`;$('count').textContent=`${photos.length}枚`;
renderChapters();renderPhotos();draw();if(photos.length){let short=plan.some(s=>s.duration<2),long=plan.some(s=>s.duration>12);say(short?'写真が多いため、1枚あたりの表示が短くなっています。動画の長さを増やすか写真を減らしてください。':long?'構成できました。写真が少ない章は長めに表示されます。写真の追加や章の調整ができます。':'構成できました。再生で確認して、動画を書き出してください。');}}
function renderChapters(){$('chapters').replaceChildren();templates[template].chapters.forEach((c,i)=>{let a=plan.filter(s=>s.p.chapter===i);const e=document.createElement('div');e.className='chapter';const b=document.createElement('strong');b.textContent=c;e.append(b,document.createTextNode(a.length?`${a.length}枚 · ${Math.round(a.reduce((v,s)=>v+s.duration,0))}秒`:'写真なし'));$('chapters').append(e);});}
function renderPhotos(){$('photos').replaceChildren();if(!photos.length){$('photos').innerHTML='<div class="timeline-empty">追加した写真がここに並びます。</div>';return;}photos.forEach((p,i)=>{const el=document.createElement('article');el.className='photo';const im=document.createElement('img');im.src=p.url;im.alt=p.name;const body=document.createElement('div');body.className='photo-body';const tools=document.createElement('div');tools.className='photo-tools';const n=document.createElement('span');n.textContent=`${i+1} · ${Math.round(plan.find(s=>s.p===p)?.duration||0)}秒`;tools.append(n);[['←',-1],['→',1],['×',0]].forEach(([label,d])=>{const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',d?`${i+1}枚目を${d<0?'前':'後'}へ`:`${i+1}枚目を削除`);b.disabled=d<0?i===0:d>0?i===photos.length-1:false;b.onclick=()=>{if(recording)return;if(d){[photos[i],photos[i+d]]=[photos[i+d],photos[i]];}else{URL.revokeObjectURL(p.url);photos.splice(i,1);}compose();};tools.append(b);});const select=document.createElement('select');select.setAttribute('aria-label',`${i+1}枚目の章`);templates[template].chapters.forEach((c,j)=>{const o=new Option(c,j);select.add(o);});select.value=p.chapter;select.onchange=()=>{p.chapter=+select.value;compose();};const caption=document.createElement('input');caption.placeholder='テロップを入力（任意）';caption.maxLength=28;caption.value=p.caption;caption.setAttribute('aria-label',`${i+1}枚目のテロップ`);caption.oninput=()=>{p.caption=caption.value;invalidate();draw();};body.append(tools,select,caption);el.append(im,body);$('photos').append(el);});}
async function addFiles(list){if(recording)return;pause();const files=Array.from(list).slice(0,100-photos.length);if(!files.length){say('写真は最大100枚です。');return;}say('写真を読み込んでいます…');let errors=0;for(const file of files){if(!file.type.startsWith('image/')){errors++;continue;}let sourceURL=URL.createObjectURL(file);try{const img=new Image();img.src=sourceURL;await img.decode();const scale=Math.min(1,1920/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('変換失敗');const url=URL.createObjectURL(blob),small=new Image();small.src=url;await small.decode();photos.push({name:file.name,url,img:small,chapter:null,caption:''});}catch{errors++;}finally{URL.revokeObjectURL(sourceURL);}}compose();if(errors)say(`${errors}枚は読み込めませんでした。JPEGまたはPNGに変換してお試しください。`);$('files').value='';}
function fitText(text,y,size,maxWidth){ctx.font=`600 ${size}px system-ui,sans-serif`;ctx.textAlign='center';ctx.fillStyle='white';const chars=Array.from(text);let lines=[],line='';chars.forEach(c=>{if(ctx.measureText(line+c).width>maxWidth&&line){lines.push(line);line=c;}else line+=c;});if(line)lines.push(line);lines.slice(0,2).forEach((l,i)=>ctx.fillText(l,canvas.width/2,y+i*size*1.5));}
function draw(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#101a2c';ctx.fillRect(0,0,w,h);if(photos.length){const s=plan.find(s=>time>=s.start&&time<s.end)|| (time<plan[0].start?plan[0]:plan[plan.length-1]);const im=s.p.img;const factor=Math.min(w/im.width,h/im.height);let dw=im.width*factor,dh=im.height*factor;ctx.drawImage(im,(w-dw)/2,(h-dh)/2,dw,dh);const font=Math.round(w*.035);if(time<plan[0].start){ctx.fillStyle='rgba(8,16,32,.55)';ctx.fillRect(0,0,w,h);fitText($('title').value||'大切な思い出',h*.47,font*1.6,w*.85);fitText(templates[template].name,h*.61,font*.7,w*.85);}else{const grad=ctx.createLinearGradient(0,h*.65,0,h);grad.addColorStop(0,'transparent');grad.addColorStop(1,'rgba(0,0,0,.8)');ctx.fillStyle=grad;ctx.fillRect(0,h*.65,w,h*.35);ctx.textAlign='left';ctx.font=`500 ${font*.6}px system-ui`;ctx.fillStyle='#dce7ff';ctx.fillText(s.chapter,w*.06,h*.88);if(s.p.caption)fitText(s.p.caption,h*.78,font,w*.86);if(time>total-5){fitText(ending(),h*.62,font,w*.85);}}}$('seek').value=time;$('clock').textContent=`${clock(time)} / ${clock(total)}`;}
function ending(){if(template===3)return 'ご覧いただきありがとうございました';if(template===4)return 'ありがとうの気持ちを込めて';if($('tone').value==='記録的')return '記録の終わり';return $('audience').value==='本人'?'これからも、大切な一歩を。':'大切な時間を、これからも。';}
function tick(ts){if(!playing)return;time+=Math.min((ts-last)/1000,1);last=ts;if(time>=total){time=total;draw();pause();if(recording&&recorder?.state==='recording')recorder.stop();return;}draw();if(recording)$('progress').value=time/total*100;raf=requestAnimationFrame(tick);}
function pause(){playing=false;cancelAnimationFrame(raf);$('play').textContent='▶';audioEl?.pause();}
async function initAudio(){if(!audioFile)return;if(!audioEl){audioURL=URL.createObjectURL(audioFile);audioEl=new Audio(audioURL);audioEl.loop=true;}if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();destination=audioCtx.createMediaStreamDestination();}if(!audioSource){audioSource=audioCtx.createMediaElementSource(audioEl);audioSource.connect(destination);audioSource.connect(audioCtx.destination);}await audioCtx.resume();}
async function play(){if(!photos.length)return;try{await initAudio();if(time>=total)time=0;if(audioEl){audioEl.currentTime=Number.isFinite(audioEl.duration)?time%audioEl.duration:0;await audioEl.play();}playing=true;last=performance.now();$('play').textContent='Ⅱ';raf=requestAnimationFrame(tick);}catch(e){say('音声を再生できませんでした。別の音源を選ぶか、BGMなしでお試しください。');if(recording){cancelled=true;recorder?.stop();}}}
async function exportVideo(){if(!photos.length||recording)return;if(!canvas.captureStream||!window.MediaRecorder){say('このブラウザでは書き出せません。最新のChromeまたはSafariでお試しください。');return;}pause();invalidate();try{await initAudio();const type=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!type)throw Error('対応する動画形式がありません');const stream=canvas.captureStream(30);if(audioFile&&destination)destination.stream.getAudioTracks().forEach(t=>stream.addTrack(t));let chunks=[];recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:4000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=()=>{cancelled=true;say('書き出しに失敗しました。短い動画でお試しください。');if(recorder.state!=='inactive')recorder.stop();};recorder.onstop=()=>{pause();stream.getVideoTracks().forEach(t=>t.stop());recording=false;document.body.classList.remove('busy');$('cancel').hidden=true;$('progress').hidden=true;$('play').disabled=false;$('seek').disabled=false;$('export').disabled=false;wake?.release();wake=null;if(cancelled){say('書き出しを中止しました。');return;}const blob=new Blob(chunks,{type:recorder.mimeType||type});if(!blob.size){say('動画を保存できませんでした。もう一度お試しください。');return;}downloadURL=URL.createObjectURL(blob);$('download').href=downloadURL;$('download').download=`フォトストーリー.${type.includes('mp4')?'mp4':'webm'}`;$('download').hidden=false;say('動画ができました。「動画を保存」を押してください。');};recording=true;cancelled=false;document.body.classList.add('busy');time=0;draw();$('cancel').hidden=false;$('progress').hidden=false;$('progress').value=0;$('export').disabled=true;$('play').disabled=true;$('seek').disabled=true;say('書き出し中です。画面を開いたままお待ちください。');try{wake=await navigator.wakeLock?.request('screen');}catch{}recorder.start(1000);await play();}catch(e){recording=false;document.body.classList.remove('busy');say(`書き出せませんでした：${e.message}`);}}
$('files').onchange=e=>addFiles(e.target.files);$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();addFiles(e.dataTransfer.files);};$('compose').onclick=compose;$('play').onclick=()=>playing?pause():play();$('seek').oninput=e=>{pause();time=+e.target.value;draw();};['length','ratio','audience','tone'].forEach(id=>$(id).onchange=compose);$('title').oninput=()=>{invalidate();draw();};$('export').onclick=exportVideo;$('cancel').onclick=()=>{cancelled=true;if(recorder?.state==='recording')recorder.stop();};$('audio').onchange=e=>{pause();invalidate();audioSource?.disconnect();audioSource=null;audioEl=null;if(audioURL)URL.revokeObjectURL(audioURL);audioFile=e.target.files[0]||null;say(audioFile?'BGMを追加しました。プレビューで音を確認してください。':'BGMなしにしました。');};document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording){cancelled=true;recorder?.stop();}else if(document.hidden)pause();});window.addEventListener('beforeunload',e=>{if(recording){e.preventDefault();e.returnValue='';}});
drawTemplates();compose();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_video_project',description:'現在の目的、写真枚数、動画時間、章構成を読み取ります。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({template:templates[template].name,photoCount:photos.length,duration:total,chapters:templates[template].chapters})})).catch(()=>{});}catch{}}
